#!/bin/bash

# Set Variables
PROGS='StorageManager workernode controllernode PrimProc ExeMgr DMLProc DDLProc WriteEngineServer'
MCS_INSTALL_BIN=/usr/bin

# Stop System
echo Stopping...

/etc/init.d/mariadb stop

if  [[ ! -z $(pidof $PROGS) ]]; then
   $MCS_INSTALL_BIN/save_brm

   echo Sending SIGTERM To Columnstore Processes
   kill $(pidof $PROGS) > /dev/null 2>&1
   sleep 3
   counter=1
   while [ -n "$(pidof StorageManager)" ] && [ $counter -le 60 ]
   do
     sleep 1
     ((counter++))
   done
   echo Sending SIGKILL To ColumnStore Processes
   kill -9 $(pidof $PROGS) > /dev/null 2>&1
fi

# Clearing Shared Memory
echo Clearing shared memory
$MCS_INSTALL_BIN/clearShm

exit 0
