#!/bin/sh

color_normal=$(tput sgr0)
color_bold=$(tput bold)
color_red="$color_bold$(tput setaf 1)"
color_green="$color_bold$(tput setaf 2)"

check_service() {
    if systemctl is-active --quiet $1; then
        echo "$1 service $color_green OK $color_normal"
    else
        echo "$1 service $color_red failed $color_normal"
        service $1 status
    fi
}

mkdir -p /run/mysqld && chown -R mysql:mysql /run/mysqld
mkdir -p /run/mariadb && chown -R mysql:mysql /run/mariadb

echo "ColumnStore Starting..."
systemctl start mariadb-columnstore.service
check_service mariadb-columnstore
echo "MariaDB Starting..."
systemctl start mariadb.service
check_service mariadb

exit 0
