#!/bin/sh

color_normal=$(tput sgr0)
color_bold=$(tput bold)
color_red="$color_bold$(tput setaf 1)"
color_green="$color_bold$(tput setaf 2)"

check_service() {
    if systemctl is-active --quiet $1; then
        echo "$1 service $color_green OK $color_normal"
    else
        echo "$1 service $color_red failed $color_normal"
        service $1 status
    fi
}

check_service mariadb-columnstore
check_service mariadb
